# Generated by Django 4.2.3 on 2023-07-30 06:51

import api_v1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('recordAdded', models.DateTimeField(auto_now_add=True)),
                ('recordModified', models.DateTimeField(auto_now=True)),
                ('studentId', models.CharField(default=api_v1.models.generateUUID, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobileNo', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('recordAdded', models.DateTimeField(auto_now_add=True)),
                ('recordModified', models.DateTimeField(auto_now=True)),
                ('subjectCode', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='studentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordAdded', models.DateTimeField(auto_now_add=True)),
                ('recordModified', models.DateTimeField(auto_now=True)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.student')),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.subjects')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordAdded', models.DateTimeField(auto_now_add=True)),
                ('recordModified', models.DateTimeField(auto_now=True)),
                ('subjectCode', models.CharField(max_length=200)),
                ('lectureDate', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
